# .github/workflows/ci.yml

name: Data Processing with Google Sheets

# Wykonuj akcje przy każdym pushu do gałęzi main
on:
  push:
    branches:
      - main

jobs:
  download-script:
    # Uruchom tylko, gdy wiadomość commitu zawiera 'deploy'
    if: contains(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest
    steps:

      # Checkout repo i pobranie skryptu z głównego zadania
      - uses: actions/checkout@v3
      - name: Clone repo with script
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git clone https://$PAT_TOKEN@github.com/PJATK-ASI-2024/Lab2---Obr-bka-danych.git
      #    cp Lab2---Obr-bka-danych/generator_danych.py .

      # Setup pythona
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Instalacja bibliotek
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Set up dostepów do Google Sheets
      - name: Set up Google Sheets credentials
        run: |
          echo "${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}" | base64 -d > creds.json

      # Generowanie pliku csv z pobranego repo
      - name: Run data processing script
        run: |
          python Lab2---Obr-bka-danych/generator_danych.py -s 25853

      # Odczyt pliku csv oraz upload danych do Google Sheets
      - name: Run data processing script
        run: |
          python s25853.py --upload './data_student_25853.csv'

      # Odczyt danych z Google Sheets oraz zwrócenie danych po czyszczeniu i standaryzacji na wyjście
      - name: Run data processing script
        run: |
          python s25853.py --standardize

      # Wyświetlenie raportu po przetwarzaniu
      - name: Display report
        run: |
          cat report.txt